### ISSUE TITLE
What permissions are needed in netbox to see the "status" and "lldp neighbors" tab on a device?

### ISSUE THREAD

**Issue by sliddjur** [netbox-community/netbox-napalm-plugin#26]
**NetBox version**
`3.6.5`

**Describe the bug**
When I am logged into my user, which has all permissions, I can not see the Status and LLDP Neighbors tab.
It works when I am logged in with the default admin user.

**To Reproduce**
- Install netbox napalm
- add to `local_requirements.txt`, and add plugin to `configuration.py`
- Run `./upgrade.sh` in netbox
- Create oauth user, using Azure as backend.
- Create group and map to my user.
- Create permissions and map to group. (Ctrl+A for all permissions)
- Check all: Can view, can add, can change, can delete.
Which includes object type `NetBox Napalm Plugin > Napalm Platform Config`

**Expected behavior**
I expect to see the Status tab and LLDP Neighbor tab under device when I am logged in with my regular user aswell

**Screenshots**
It works with admin user
![image](https://github.com/netbox-community/netbox-napalm/assets/10002057/b84bc6eb-9a68-47ab-a6a3-102bb6ab4228)

**Additional context**
Maybe related to something in Netbox, as I am having similar problems with https://miaow2.github.io/netbox-config-diff/ netbox config diff plugin.

**Comment by cbeytas** [comment]
You may need to add a permission. This should be in the documentation!
https://github.com/netbox-community/netbox/discussions/8709

**Comment by cruse1977** [comment]
dcim.napalm_read_device ?
