### ISSUE TITLE
Netbox 3.7.0 Support

### ISSUE THREAD

**Issue by cmcknz77** [netbox-community/netbox-napalm-plugin#27]
Plugin doesn't support Netbox 3.7.0

Amend max_version = '3.6.99' line in https://github.com/netbox-community/netbox-napalm/tree/main/netbox_napalm_plugin/__init__.py

**Comment by peteeckel** [comment]
Hi @arthanson, I (like many others) ran into the same issue (again).

I don't see much use in setting the maximum NetBox version for the (or any) plugin anymore, given the fact that you and the rest of the core team do an awesome job of keeping the plugin API stable. I just removed it from `__init__.py`, and the plugin works perfectly.

IMHO the maximum version seeting causes more trouble than I've ever had with real incompatibilities these days, and would suggest to remove that limitation.

**Comment by robertlynch3** [comment]
Added support in #28. I agree max version does add some extra headache. Is it a benefit that each version basically needs to be validated that its supported? Does it reduce user error when its not actually supported?

**Comment by arthanson** [comment]
Just updated the package, will research about removing the check...

**Comment by DanSheps** [comment]
IMO, it is better to keep that max check, just because it prevents an issue of someone assuming an un-maintained plugin (not saying this is unmaintained) will work with a newer version of NetBox.

IMO, we should maybe look at adding a plugin check to the netbox upgrade script to bail if not all plugins are up-to-date for the current version of NetBox so it doesn't do a partial upgrade.

**Comment by peteeckel** [comment]
@DanSheps On the other hand the max version check would not have prevented the only incompatibility I experienced in more than a year: The broken import in NetBox 3.5.8.

The upgrade check is a good idea, however not everyone is using the upgrade script. I'm thinking about Docker users and myself - I roll out the complete environment via Ansible, creating a fresh installation tree with each major upgrade.

**Comment by andrey-zap81** [comment]
Hey Guys, so is there any new release coming soon? i want to use latest Netbox (v3.7.3) and I get the error
Plugin netbox_napalm_plugin requires NetBox maximum version 3.6.99,
I saw a commit to master an hour ago here =)
https://github.com/netbox-community/netbox-napalm-plugin/blob/main/netbox_napalm_plugin/__init__.py#L25

**Comment by arthanson** [comment]
@andrey-zap81 The plugin version 0.1.7 released in January should be updated to work for NetBox 3.7, just do a `pip install --upgrade netbox-napalm-plugin` in your NetBox virtual environment.
