### ISSUE TITLE
Error connecting to device

### ISSUE THREAD

**Issue by heidl89** [netbox-community/netbox-napalm-plugin#31]
Hello

I have a problem to display the data in the gui. 

I got the message: 

Pattern not detected: 'S\\-01\\-EN02\\-E141' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

If i enter the cli and execute the debug command, i see the data in the cli. 

Thx!

**Comment by cruse1977** [comment]
Hi,  please provide more detail - device type, network device os, hostname also what command you run to see the data in the cli.

**Comment by heidl89** [comment]
Hi, thx for your response :) 
The problem was in my config with the host-name...
