### ISSUE TITLE
After installing the plugin the website fail to locate the *.js files

### ISSUE THREAD

**Issue by ntaken** [netbox-community/netbox-napalm-plugin#33]
### NetBox Napalm Plugin version

v.0.1.8

### NetBox version

v3.7.6

### Python version

3.8

### Steps to Reproduce

![pic](https://github.com/netbox-community/netbox-napalm-plugin/assets/71373110/d6285fa5-67fa-4503-a0c5-ddb66031cb5e)

Added the plugin to local_requirements.txt, ran upgrade.sh and reloaded netbox services + added correct stuff to conf file.

As the picture shows it seems that the website is looking for the file at the wrong location.

### Expected Behavior

show the new page when pressing status tab.

### Observed Behavior

Static Media Failure
The following static media file failed to load: [status.js](https://netbox.unikom.se/static/status.js)

Check the following:

    manage.py collectstatic was run during the most recent upgrade. This installs the most recent iteration of each static file into the static root path.
    The HTTP service (e.g. nginx or Apache) is configured to serve files from the STATIC_ROOT path. Refer to [the installation documentation](https://docs.netbox.dev/en/stable/installation/) for further guidance.
        STATIC_ROOT: /opt/netbox/netbox/static
        STATIC_URL: /static/
    The file status.js exists in the static root directory and is readable by the HTTP server.

Click [here](https://netbox.unikom.se/) to attempt loading NetBox again.

**Comment by tooeffayy** [comment]
I checked the tar distributed through pip and the latest (1.8) is missing the static files entirely from the download.

**Comment by K3ndu** [comment]
Same problem here

**Comment by cyberndj** [comment]
+1 for same issues....

**Comment by arthanson** [comment]
@ntaken, @tooeffayy, @K3ndu, @cyberndj should hopefully be fixed in latest v0.1.9 release.

**Comment by K3ndu** [comment]
Yes, 0.1.9 works again

**Comment by arthanson** [comment]
closing as fixed in v0.1.9
