### ISSUE TITLE
NetBox Napalm Plugin stopped working on netbox v4.0.1.

### ISSUE THREAD

**Issue by ntaken** [netbox-community/netbox-napalm-plugin#35]
### NetBox Napalm Plugin version

v.0.2

### NetBox version

v4.0.1

### Python version

3.10

### Steps to Reproduce

I upgraded from an working v3.7.8 and with NetBox Napalm Plugin version v0.1.9.

I have gotten version v.0.2 and napalm works from cli inside netbox venv.

Does the plugin work for someone else on netbox v4

### Expected Behavior

That the plugin displays collected info from device.

### Observed Behavior

I can see and use the pages(Status, LLDP Neighbors, Config) on the device in netbox but I only see the static text with no text collected from the device with napalm.

**Comment by willikubny** [comment]
I have exactly the same issue as described with NetBox version v4.0.1 and the NetBox Napalm Plugin v0.2.0

**Comment by ssigle** [comment]
Same issue here.

Netbox 4.0.1
netbox-napalm-plugin 0.2.0
napalm 4.1.0
Python 3.10.12
Ubuntu 22.04.4

**Comment by cruse1977** [comment]
Hi, based on the compatibility matrix within the readme, the plugin is not yet certified against 4.x

**Comment by willikubny** [comment]
> Hi, based on the compatibility matrix within the readme, the plugin is not yet certified against 4.x

The readme have not been updated I guess.
There is a release v0.2.0 with the comment that support for Netbox v4.0 have been addded.
(https://github.com/netbox-community/netbox-napalm-plugin/releases/tag/v0.2.0)

**Comment by cruse1977** [comment]
> > Hi, based on the compatibility matrix within the readme, the plugin is not yet certified against 4.x
> 
> The readme have not been updated I guess. There is a release v0.2.0 with the comment that support for Netbox v4.0 have been addded. (https://github.com/netbox-community/netbox-napalm-plugin/releases/tag/v0.2.0)



> > Hi, based on the compatibility matrix within the readme, the plugin is not yet certified against 4.x
> 
> The readme have not been updated I guess. There is a release v0.2.0 with the comment that support for Netbox v4.0 have been addded. (https://github.com/netbox-community/netbox-napalm-plugin/releases/tag/v0.2.0)

Spent time debugging this. This commit; [jeremystretch/netbox@239d218](https://github.com/netbox-community/netbox/commit/239d21870b00a3336549806773a25d888039fba4) removes the data div from base.html which breaks the js.

**Comment by cruse1977** [comment]
PR above. Tested on 4.0.3 but should work on 4.0.2.  The issue was template changes in I think 3.7.6; which removed a block replied upon by the plugin.  Hardcoded this into the templates + tweaked the javascript to use more common functionality in finding the URL to run.
